flow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from allauth.account import views
from flow_measurement.views import parameters
from flow_measurement.views import get_temp_press
from flow_measurement.views import get_todays_date
from flow_measurement.views import save_results

from flow_measurement.views import MainPage, MeasurementView, SettingsView
from flow_measurement.views import InfoView
from flow_measurement.views import (
    StationListView, DeviceListView,
    StationCreateView, DeviceCreateView,
    StationDetailView,
    DeviceDeleteView, StationDeleteView
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login, name='index'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^main/', MainPage.as_view(), name='main-page'),
    url(r'^measurement/$', MeasurementView.as_view(), name='measurement'),
    url(r'^settings/$', SettingsView.as_view(), name='settings'),
    url(r'^info/$', InfoView.as_view(), name='info'),
    url(r'^stations/(?P<pk>\d+)/$', StationDetailView.as_view(), name='detail-station'),
    url(r'^stations/delete/(?P<pk>\d+)/$', StationDeleteView.as_view(), name='delete-station'),
    url(r'^stations/add/$', StationCreateView.as_view(), name='add-station'),
    url(r'^stations/$', StationListView.as_view(), name='stations'),
    url(r'^devices/delete/(?P<pk>\d+)/', DeviceDeleteView.as_view(), name='delete-device'),
    url(r'^devices/add/$', DeviceCreateView.as_view(), name='add-device'),
    url(r'^devices/$', DeviceListView.as_view(), name='devices'),

    url(r'^parameters/$', parameters, name='parameters'),
    url(r'^get_temp_press/$', get_temp_press, name='get-temp-press'),
    url(r'^get_todays_date/$', get_todays_date, name='todays-date'),
    url(r'^save_results/$', save_results, name='save-results'),
]

flow_measurement/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model

UserModel = get_user_model()


class Station(models.Model):
    name = models.CharField(max_length=30)
    longitude = models.FloatField()
    latitude = models.FloatField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stations')


class Device(models.Model):
    name = models.CharField(max_length=40)
    serial_number = models.CharField(max_length=35)
    station = models.ForeignKey('Station', null=True, blank=True, on_delete=models.SET_NULL)
    TYPES_OF_DEVICES = (
        ('reference_dev', 'reference device'),
        ('measured_dev', 'measured device'),
        ('regulator', 'regulator'),
    )
    dev_type = models.CharField(max_length=20, choices=TYPES_OF_DEVICES)

    def __str__(self):
        return "{0}, {1}".format(self.name, self.serial_number)

    def get_absolute_url(self):
        return reverse('devices')


class ResultDevice(models.Model):
    volume = models.FloatField()
    flowrate = models.FloatField()
    device = models.ForeignKey('Device', on_delete=models.CASCADE)

    def __str__(self):
        return "{0} - {1} - {2}".format(
            self.device, self.volume, self.flowrate)


class Result(models.Model):
    user = models.ForeignKey(UserModel)
    measurement_date = models.DateTimeField()
    measurement_time = models.DurationField()
    temperature = models.FloatField()
    pressure = models.FloatField()
    error = models.FloatField()
    station = models.ForeignKey('Station')
    reference_device = models.ForeignKey(
        'ResultDevice', related_name='reference_device',
        on_delete=models.CASCADE)
    measured_device = models.ForeignKey(
        'ResultDevice', related_name='measured_device',
        on_delete=models.CASCADE)

    def __str__(self):
        return '{0} - {1} - {2} - {3} - {4}'.format(
            self.measurement_date, self.user, self.station, self.measured_device, self.error)

flow_measurement/forms.py
import datetime

from django import forms

from flow_measurement.models import Device, Station

class DeviceForm(forms.ModelForm):
    name = forms.CharField(label='name', max_length=35)
    serial_number = forms.CharField(label='serial number', max_length=35)
    TYPES_OF_DEVICES = (
        ('reference_dev', 'reference device'),
        ('measured_dev', 'measured device'),
        ('regulator', 'regulator'),
    )
    dev_type = forms.ChoiceField(label='device type', choices=TYPES_OF_DEVICES)
    station = forms.ModelChoiceField(label='station', required=False,  queryset=Station.objects.all())

    class Meta:
        model = Device
        fields = ['name', 'serial_number', 'dev_type', 'station']


class StationForm(forms.ModelForm):
    name = forms.CharField(label='name', max_length=40)
    longitude = forms.FloatField(label='longitude')
    latitude = forms.FloatField(label='latitude')

    class Meta:
        model = Station
        fields = ['name', 'longitude', 'latitude']

flow_measurement/views.py
import datetime
import time
import json
import requests

from django.views.generic import TemplateView, ListView,\
        CreateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from .models import Station, Device, Result, ResultDevice
from .forms import DeviceForm, StationForm

import logging
logging.basicConfig(level=logging.DEBUG)


class MainPage(TemplateView):
    template_name = 'flow_measurement/main.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MainPage, self).dispatch(*args, **kwargs)


class MeasurementView(TemplateView):
    template_name = 'flow_measurement/measurement.html'
    model = Station

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MeasurementView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MeasurementView, self).get_context_data(**kwargs)
        context['stations'] = Station.objects.all()
        context['reference_devices'] = Device.objects.filter(
            dev_type='reference_dev'
        )
        context['measured_devices'] = Device.objects.filter(
            dev_type='measured_dev'
        )
        return context


class SettingsView(TemplateView):
    template_name = 'flow_measurement/settings.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SettingsView, self).dispatch(*args, **kwargs)


class InfoView(TemplateView):
    template_name = 'flow_measurement/info.html'


class StationListView(ListView):
    model = Station

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(StationListView, self).dispatch(*args, **kwargs)


class StationDetailView(DetailView):
    model = Station

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(StationDetailView, self).dispatch(*args, **kwargs)


class StationCreateView(CreateView):
    template_name = 'flow_measurement/forms/station_create_form.html'
    model = Station
    form_class = StationForm


class StationDeleteView(DeleteView):
    model = Station
    template_name = 'flow_measurement/forms/confirm_delete.html'
    success_url = reverse_lazy('stations')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(StationDeleteView, self).dispatch(*args, **kwargs)


class DeviceListView(ListView):
    model = Device

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeviceListView, self).dispatch(*args, **kwargs)


class DeviceCreateView(CreateView):
    template_name = 'flow_measurement/forms/device_create_form.html'
    model = Device
    form_class = DeviceForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeviceCreateView, self).dispatch(*args, **kwargs)


class DeviceDeleteView(DeleteView):
    model = Device
    template_name = 'flow_measurement/forms/confirm_delete.html'
    success_url = reverse_lazy('devices')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeviceDeleteView, self).dispatch(*args, **kwargs)


def parameters(request):
    P_ST = 1013
    T_ST = 293
    if request.method == 'POST':
        try:
            station_id = request.POST.get('station')
            station = Station.objects.get(id=station_id)
            station_name = station.name
            ref_dev_id = request.POST.get('referenced_device')
            ref_dev = Device.objects.get(id=ref_dev_id)
            meas_dev_id = request.POST.get('measured_device')
            meas_dev = Device.objects.get(id=meas_dev_id)
            temperature = float(request.POST.get('temperature'))
            temp_k = temperature + 273
            pressure = float(request.POST.get('pressure'))
            meas_date = request.POST.get('measurement_date')
            meas_time = request.POST.get('measurement_time')
            ref_dev_volume = float(request.POST.get('refDevVolume'))
            meas_dev_volume = float(request.POST.get('measDevVolume'))
            coeff = (P_ST * temp_k)/(T_ST * pressure)
            tcv = ref_dev_volume * coeff
            flowrate_ref_dev = get_flowrate(ref_dev_volume, meas_time)
            flowrate_meas_dev = get_flowrate(meas_dev_volume, meas_time)
            coefficient = format(coeff, '.4f')
            error = format((((meas_dev_volume - tcv) / tcv) * 100), '.2f')
            json_data = {
                'station': station_name,
                'reference_device': ref_dev,
                'measured_device': meas_dev,
                'temperature': temperature,
                'pressure': pressure,
                'measurement_date': meas_date,
                'measurement_time': meas_time,
                'ref_dev_volume': ref_dev_volume,
                'meas_dev_volume': meas_dev_volume,
                'flowrate_ref_dev': flowrate_ref_dev,
                'flowrate_meas_dev': flowrate_meas_dev,
                'coefficient': coefficient,
                'theoretical_controller_volume': tcv,
                'error': error
            }
        except ValueError as e:
            message = str(e)
            return JsonResponse({"message": message})

        return render(request, 'flow_measurement/results.html', json_data)
    else:
        return HttpResponseRedirect(reverse('main-page'))


def save_results(request):
    P_ST = 1013
    T_ST = 293
    if request.method == 'POST':
        referenced_device_id = request.POST.get('referenced_device')
        referenced_device = Device.objects.get(id=referenced_device_id)
        measured_device_id = request.POST.get('measured_device')
        measured_device = Device.objects.get(id=measured_device_id)
        temperature = float(request.POST.get('temperature'))
        temp_k = temperature + 273
        pressure = float(request.POST.get('pressure'))
        measurement_time = request.POST.get('measurement_time')
        referenced_volume = float(request.POST.get('refDevVolume'))
        measured_volume = float(request.POST.get('measDevVolume'))
        coeff = (P_ST * temp_k)/(T_ST * pressure)
        tcv = referenced_volume * coeff
        referenced_flowrate= get_flowrate(referenced_volume, measurement_time)
        measured_flowrate= get_flowrate(measured_volume, measurement_time)
        error = format((((measured_volume - tcv) / tcv) * 100), '.2f')
        result_referenced_device = ResultDevice.objects.create(
            volume=referenced_volume,
            flowrate=referenced_flowrate,
            device=referenced_device
        )
        result_measured_device = ResultDevice.objects.create(
            volume=measured_volume,
            flowrate=measured_flowrate,
            device=measured_device
        )
        result_referenced_device.save()
        result_measured_device.save()
        station_id = request.POST.get('station')
        station = Station.objects.get(id=station_id)
        user = request.user
        measurement_date = request.POST.get('measurement_date')
        measurement_time_str = request.POST.get('measurement_time')
        measurement_time = get_time(measurement_time_str)
        temperature = request.POST.get('temperature')
        pressure = request.POST.get('pressure')
        reference_device = result_referenced_device
        measured_device = result_measured_device
        result = Result.objects.create(
            user=user,
            measurement_date=measurement_date,
            measurement_time=measurement_time,
            temperature=temperature,
            pressure=pressure,
            error=error,
            station=station,
            reference_device=reference_device,
            measured_device=measured_device,
        )
        result.save()
        return JsonResponse({'success': True})


def get_time(time_str):
    time_list = time_str.split(':')
    if len(time_list) == 2:
        hours, minutes = time_list
        measurement_time = datetime.timedelta(hours=int(hours),
                minutes=int(minutes))
    elif len(time_list) == 3:
        hours, minutes, seconds = time_list
        measurement_time = datetime.timedelta(hours=int(hours),
                minutes=int(minutes), seconds=int(seconds))
    else:
        pass
    return measurement_time


def get_temp_press(request):
    API_TOKEN = '{YOUR_API_TOKEN}'
    API_URL_BASE = 'http://api.openweathermap.org/data/2.5/weather'
    headers = {
        'Content-Type': 'application/json',
    }
    if request.method == 'POST':
        station_id = request.POST.get('station')
        coordinates = json.loads(get_coordinates(station_id))
        lat = coordinates['lat']
        lon = coordinates['lon']
        url_parameters = {
            'lat': lat,
            'lon': lon,
            'appid': API_TOKEN
        }
        response = requests.get(API_URL_BASE, params=url_parameters, headers=headers)
        data = json.loads(response.content)
        temp_k = float(data['main']['temp']) - 273
        temp = '{:.1f}'.format(temp_k)
        press = data['main']['pressure']
        json_response = {"temperature": temp, "pressure": press}
        return JsonResponse(json_response)
    else:
        return HttpResponseRedirect(reverse('main-page'))


def get_coordinates(station_id):
    station = Station.objects.get(id=station_id)
    coordinates = {
        'lat': station.latitude,
        'lon': station.longitude
    }
    json_data = json.dumps(coordinates)
    return json_data


def get_todays_date(request):
    current_date = datetime.date.today()
    json_date = {
        'current_date': current_date

templates/flow_measurement/device_list.html
{% extends "base_left_menu.html" %}

{% block head_title %}devices{% endblock head_title %}

{% block head %}
<style>
.modal-body .container {
    padding: 5%;
    height: auto;
    width: auto;
}
.modal-header {
    text-align: center;
    vertical-align: middle;
}
.css-serial {
  counter-reset: serial-number;
}

.css-serial th:first-child:before {
  counter-increment: serial-number;
  content: counter(serial-number);
}
</style>
{% endblock head %}

{% block content %}
<div class="col-sm-7">
    <h3 class="mb-3">devices</h3>
    <table class="table">
      {% if object_list %}
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">name</th>
          <th scope="col">serial number</th>
          <th scope="col">type</th>
          <th scope="col">station</th>
        </tr>
      </thead>
      {% endif %}
      <tbody class="css-serial">
        {% for device in object_list %}
        <tr>
          <th scope="row"></th>
          <td class="align-middle">{{ device.name }}</td>
          <td class="align-middle">{{ device.serial_number }}</td>
          <td class="align-middle">{{ device.get_dev_type_display }}</td>
          {% if device.station %}
            <td class="align-middle"><a href="{% url 'detail-station' device.station.pk %}"> {{ device.station.name }} </a></td>
          {% else %}
            <td>no station</td>
          {% endif %}
          <td class="col-md-1"></td>
          <td><a class="btn btn-link text-warning" href="#">edit</a> </td>
          <td><a class="btn btn-link text-danger" href="{% url 'delete-device' device.pk %}">delete</a> </td>
        </tr>
        {% empty %}
            <p>no devices in the database</p>
        {% endfor %}
      </tbody>
</table>

    <button role="button" class="btn btn-primary mt-4" data-toggle='modal' data-target='#add-device-modal'>add device</button>
</div>
{% endblock content %}

{% block modals %}
<div class="modal" id="add-device-modal" tabindex="-1"></div>

<script>
$('#add-device-modal').on('show.bs.modal', function (event) {
    var modal = $(this)
    $.ajax({
        url: "{% url 'add-device' %}",
        context: document.body
    }).done(function(response) {
        modal.html(response);
    });
})
</script>
{% endblock modals %}

templates/flow_measurement/info.html
{% extends "base_left_menu.html" %}

{% block content %}
<div class="col-sm-7">
	<h3> Info </h3>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
{% endblock content %}

templates/flow_measurement/main.html
{% extends "base.html" %}

{% block style %}
{% endblock style %}

{% block head %} {% endblock head %}

{% block content %}
	<div class="col-md-4">
        <a role="button" class="btn btn-block py-1" href="{% url 'measurement' %}">measurements</a>
        <a role="button" class="btn btn-block py-1" href="{% url 'settings' %}">settings</a>
        <a role="button" class="btn btn-block py-1" href="{% url 'info' %}">information</a>

        <a role="button" class="btn btn-block mt-4" href="{% url 'account_logout' %}">log out</a>
    </div>
{% endblock %}

templates/flow_measurement/measurement.html
{% extends "base_left_menu.html" %}
{% block head_title %}measurement{% endblock head_title %}
{% block head %}
<style>
h2 {
    margin-bottom: 20px;
}
.hidden {
    visibility: hidden;
}
.visible {
    visibility: visible;
}
</style>
{% endblock head %}

{% block content %}
	<div class="col-sm-7 text-center">
	    <h3 class="text-left mb-3"> Measurement </h3>
	    <form method='POST' id='values-form'> {% csrf_token %}
            <div class="form-group row">
                <select class="form-control col-sm-10" id='station' form='values-form'>
                    <option value='0'> station </option>
                {% for station in stations %}
                    <option value='{{ station.id }}'> {{ station.name }} </option>
                {% endfor %}
                </select> <a role="button" class="btn col-sm-2" href="{% url 'add-station' %}">add</a>
            </div>
            <div class="form-group row">
            <select class="form-control col-sm-10" id='referenced-device' form='values-form'>
                <option value='0'> reference device </option>
            {% for device in reference_devices %}
            <option value='{{ device.id }}'> {{ device.name }}, {{ device.serial_number }}
            </option>
            {% endfor %}
            </select><a role="button" class="btn col-sm-2" href="{% url 'add-device' %}">add</a>
            </div>
            <div class="form-group row">
            <select class="form-control col-sm-10" id='measured-device' form='values-form'>
                <option value='0'> measured device </option>
            {% for device in measured_devices %}
            <option value='{{ device.id }}'> {{ device.name }}, {{ device.serial_number }}
            </option>
            {% endfor %}
            </select> <a role="button" class="btn col-sm-2" href="{% url 'add-device' %}">add</a>
            </div>

				<div class="form-group row justify-content-start">
					<div class="col-sm-10 m-0 p-0 mt-3 mb-3">
                        <input class="form-control col-sm-12"
                               name='temperature' type='number' step='0.1' id='temperature' placeholder='temperature [&#176;C]' />
                        <input class="form-control col-sm-12" name='pressure' type='number' step='0.01' id='pressure' placeholder='atm. pressure [hPa]' />
					</div>
					<div class="col-sm-2 m-0 p-0 align-self-center">
                        <a role="button" id="btn-temp-press" class="btn" href="">download</a>
					</div>
				</div>
				<div class="form-group row justify-content-start">
                        <input class="form-control col-sm-10" type='date' id='measurement-date' placeholder='date of measurement' />
					<div class="col-sm-2 m-0 p-0 align-self-center">
                        <a role="button" id="btn-today" class="btn" href="">today</a>
                    </div>
				</div>

				<div class="form-group row justify-content-start">
					<input class="form-control col-sm-10" type='time' step='1'
                    id='measurement-time' placeholder='measurement time [m:s]' />
				</div>

				<div class="form-group row justify-content-start">
					<input class="form-control col-sm-10" type='number' step='0.01'
                    id='reference-device-volume' placeholder='reference device volume [dm&#179;]' />
				</div>

				<div class="form-group row justify-content-start">
					<input class="form-control col-sm-10" type='number' step='0.01'
                    id='measured-device-volume' placeholder='measured device volume [dm&#179;]' /><br />
				</div>
				<input class="btn btn-primary brn-sm mt-8" type='submit' id='submit-button' value='calculate' />
	    </form>
	</div>
	<div class="modal fade" id="resultsModal" tabindex="-1" role="dialog" aria-labelledby="resultsModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
		<h5 class="modal-title" id="resultsModalLabel">measurement results</h5>
	      </div>
	      <div class="modal-body px-auto mx-auto mw-100">
		...
	      </div>
	      <div class="modal-footer">
		<button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">cancel</button>
		<button type="button" id="btn-save-results" class="btn btn-primary btn-sm" data-dismiss="modal">save changes</button>
	      </div>
	    </div>
	  </div>
	</div>
    <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">success</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <h6>The data has been correctly saved to the database</h6>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">close</button>
          </div>
        </div>
      </div>
    </div>


<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'> </script>

<script>

$('#btn-save-results').on('click', function(e) {
    e.preventDefault();
    var data = fetch_parameters();
    $.ajax({
        type: 'POST',
        url: '/save_results/',
        data: data,
        success: function(data) {
            $('#successModal').modal('show');
        }
    });
});

$('#btn-temp-press').on('click', function(e) {
    e.preventDefault();
    getTempPress();
});

function getTempPress() {
    $.ajax({
        type: 'POST',
        url: '/get_temp_press/',
        data: {
            station: $('#station option:selected').val(),
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function(data) {
            insertValues(data);
        },
    })
}

function insertValues(data) {
    $('#temperature').val(data['temperature']);
    $('#pressure').val(data['pressure']);
}

$('#btn-today').on('click', function(e) {
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: '/get_todays_date/',
        data: {
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
        },
        success: function(data) {
            $('#measurement-date').val(data['current_date']);
        },
    })
});

function fetch_parameters(e) {
    var data_parameters = {}
    data_parameters['station'] = $('#station option:selected').val()
    data_parameters['referenced_device'] = $('#referenced-device option:selected').val()
    data_parameters['measured_device'] = $('#measured-device option:selected').val()
    data_parameters['temperature'] = $('#temperature').val()
    data_parameters['pressure'] = $('#pressure').val()
    data_parameters['measurement_date'] = $('#measurement-date').val()
    data_parameters['measurement_time'] = $('#measurement-time').val()
    data_parameters['refDevVolume'] = $('#reference-device-volume').val()
    data_parameters['measDevVolume'] = $('#measured-device-volume').val()
    data_parameters['csrfmiddlewaretoken'] = $('input[name=csrfmiddlewaretoken]').val()
    return data_parameters;
}

$('#values-form').on('submit', function(e) {
    e.preventDefault();
    data_parameters = fetch_parameters();
    addParameters();
});



function addParameters() {
    $.ajax({
        type: 'POST',
        url: '/parameters/',
        data: data_parameters,
        success: function(data) {
            displayValues(data);
        }

    })
}

function displayValues(data) {
    $('#resultsModal .modal-body').html(data);
    $('#resultsModal').modal('show');
}

function displayValuesModal() {
}

</script>

{% endblock content %}

templates/flow_measurement/results.html
<!doctype html>

<html>
<head>
<style>
table td:first-child {
    text-align: right;
    font-weight: bold;
}
table td:nth-child(2) {
    text-align: left;
    padding-left: 1em;
}
</style>
</head>

<body>
<table style="font-size: 80%">
    <tr>
        <td>station:</td> <td>{{ station }}</td>
    </tr>
    <tr>
        <td>reference device:</td> <td>{{ reference_device }}</td>
    </tr>
    <tr>
        <td>measured device:</td> <td>{{ measured_device }}</td>
    </tr>
    <tr>
        <td>temperature:</td> <td>{{ temperature }} &#8451</td>
    </tr>
    <tr>
        <td>pressure:</td> <td>{{ pressure }} hPa</td>
    </tr>
    <tr>
        <td>date:</td> <td>{{ measurement_date }} </td>
    </tr>
        <td>measurement time:</td> <td>{{ measurement_time }}</td>
    </tr>
    </tr>
    <td>reference device volume:</td> <td>{{ ref_dev_volume }} dm&#179;</td>
    </tr>
    </tr>
        <td>measured device volume:</td> <td>{{ meas_dev_volume }} dm&#179;</td>
    </tr>
    </tr>
        <td>measured device flowrate:</td> <td>{{ flowrate_ref_dev }} dm&#179;/min</td>
    </tr>
    </tr>
        <td>reference device flowrate:</td> <td>{{ flowrate_meas_dev }} dm&#179;/min</td>
    </tr>
    <tr>
        <td>coefficient:</td> <td>{{ coefficient }}</td>
    </tr>
    </tr >
        <td>measurement error:</td> <td><font color="red">{{ error }} %</font></td>
    </tr>
</table>
</body>
</html>

templates/flow_measurement/settings.html
{% extends "base_left_menu.html" %}

{% block content %}
	<div class="col-sm-7">
	    <h3> Settings </h3>
		<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
{% endblock content %}

templates/flow_measurement/station_detail.html
{% extends 'base_left_menu.html' %}

{% block content %}

<h3> {{ object.name }} </h3>

{% endblock %}